### PR TITLE
Refactor SwipeItemManager code to decouple it from adapter converns

### PR DESCRIPTION
**Pull request by mcumings**
The interactions with the BaseAdapter and RecyclerView.Adapter in the SwipeItemManagerImpl code were unnecessarily coupled to the underlying implementations.  This refactor allows API users to utilize the state management provided by SwipeItemManagerImpl without having to extend any of the utility base classes.  It also dramatically simplifies the code to attain better cohesion.

### CODE REVIEW

**Comment by daimajia** [comment]
This is an awesome code refractor! Thanks your working on this.

Before I merge this PR, i need to mention the other collaborators of this porject to let them know the change of the code, and make code review.
@linfaxin @jpshelley

**Comment by jpshelley** [comment]
@daimajia I trust you to verify it. Otherwise if you need me to I can look at it after midnight tomorrow when all my classes are done. Since we don't have the tests completed yet, I'd like to run the demo applications with it quick. First glance it looks good though.

**Comment by daimajia** [comment]
@jpshelley great!

**Comment by daimajia** [comment]
Thanks @mcumings ~

**Comment by mcumings** [comment]
No problem!  Thanks for publishing this library (and merging the PR)!

**Comment by daimajia** [comment]
@mcumings I really want to invite you to be a collaborator of this project, because you are really awesome, would you like be? :-D

**Comment by mcumings** [comment]
I appreciate the offer but respectfully decline. :)

**Comment by daimajia** [comment]
@mcumings  Respect your decision.   :sob:

**Pull request merged**
