### PR TITLE
Create recycler adapter and example

### PR DESCRIPTION
**Pull request by jpshelley**
Fix for #49 
1) Created an advanced RecyclerAdapter in the Demo to instruct people on how to use the RecyclerView.Adapter straight from the android sdk.
2) Created a simplified RecyclerAdapter in the Demo that extends from a newly created RecyclerSwipeAdapter that was created in the library.
3) Created a RecyclerViewExample activity to demonstrate the simplifies approach as well as using TwoWayView library with RecyclerView.
4) Update Library components concerning the RecyclerView and pulled the Mode attribute out to a util package.

### CODE REVIEW

**Comment by heyarny** [comment]
@jpshelley @daimajia could you fix the issues with recyclerView? I'm trying to add onClickListener, but it ignores the event in favor of swipe events. As soon I disable swipe, click events start working again.
What's the best way to fix it?

**Comment by jpshelley** [comment]
@heyarny I'm looking into it this week. Got busy with school, work, and the holidays. I believe its an underlying issue with SwipeLayout which I'll be looking in to.

**Comment by djandreski** [comment]
Hey guys here is how I implemented the `RecyclerSwipeAdapter` in my app 
https://gist.github.com/djandreski/a7e17af830d56c2f0ba6

and here is the concrete adapter implementation
https://gist.github.com/djandreski/c58070a9cc12f30da203

This is the basic implementation, all unrelated stuff like dividers, item click handling are not crucial for this library and they have to be handled by the user even for the base implementation of the RyclerView. 

I hope this helps.

**Comment by jpshelley** [comment]
@djandreski I agree its up to the end user to implement the click/dividers etc. However were you able to get clicks to work? It is a functional piece of this library and I was having issues that might be related to the underneath SwipeLayout object.

**Comment by djandreski** [comment]
@jpshelley Can you give me an example or use case about this click problem?

If you look into this Gist https://gist.github.com/djandreski/c58070a9cc12f30da203 you can see how I handle the item click in the `TaskViewHolder` inner class.
As you can see, it is handled in the implementation of the base `RecyclerSwipeAdapter`

Try it and see if it fixes your problem, it works for me.

**Comment by jpshelley** [comment]
@djandreski It looks right. I'm not disagreeing, just letting you know this struggle I was having. The issue is two-fold:

1) With RecyclerView being a new widget from android, the entire community (from what I can tell) hasn't decided on a proper way to handle 'view clicks', such as an entire view in a list consuming the click. (Your way works for an item inside the view, although I've seen it done inside the bindViewHolder() method as well.

2) Because of the first statement, I went with the more widely accepted and used method, that came from the Two-Way-View library. Which attaches a click handler to the actual RecyclerView itself in the fragment and not in the RecyclerView-Adapater.

If anyone ( @djandreski or @daimajia primarily) sees any flaws in my logic let me know.
If for sake of getting this pull request accepted, I will take @djandreski gist and incorporate it in my pull request just to show the implementation.

**Comment by djandreski** [comment]
@jpshelley Yeah Two-Way-View approach seems very valid to me, and if you say it is more popular, then I don't have any complaints about it.

**Comment by jpshelley** [comment]
@djandreski @daimajia Okay. My plan for the next week, is to spend a day trying to implement the Two-Way-View approach. If it doesn't work, for the sake of this pull request I'll use @djandreski implementation and leave it up to the end user to connect onClickListeners.

**Comment by daimajia** [comment]
@jpshelley  Cool！

**Comment by jpshelley** [comment]
@daimajia @djandreski Feel free to try my newest commits out, give them a look. And check the discussion in gitter.

**Comment by daimajia** [comment]
@jpshelley Well done, I'll check this PR right now!

**Comment by daimajia** [comment]
@jpshelley 
i think the `SwipeMemory`  and `OnLayoutListener ` should be extracted from [`SwipeItemRecyclerManagerImpl`](https://github.com/jpshelley/AndroidSwipeLayout/blob/create_recycler_adapter/library/src/main/java/com/daimajia/swipe/implments/SwipeItemRecyclerMangerImpl.java#L162-L224) and [`SwipeItemManagerImpl`](https://github.com/jpshelley/AndroidSwipeLayout/blob/create_recycler_adapter/library/src/main/java/com/daimajia/swipe/implments/SwipeItemMangerImpl.java#L164-L228).

**Comment by daimajia** [comment]
And also the class `ValueBox`.

**Comment by jpshelley** [comment]
@daimajia Ha good point! I'll do that too.

**Comment by jpshelley** [comment]
@daimajia take a look

**Comment by daimajia** [comment]
I checked every line in your PR, really excellent!

**Pull request merged**
